remote_theme: pages-themes/midnight@v0.2.0

include:
  - ".gitbook"
  
plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

  - scope:
      path: ""
      type: "pages"
      name: "README.md"
    values:
      layout: special

auto_desc: true
