remote_theme: pages-themes/midnight@v0.2.0
include:
  - ".gitbook"
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

  - scope:
      path: ""
      type: "pages"
      name: "README.md"
    values:
      layout: special
